# Generated by Django 5.0.7 on 2024-09-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='foldername',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
