# Generated by Django 5.0.8 on 2024-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_window_foldername'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
