# Generated by Django 5.0.8 on 2024-09-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_extra_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='extra_fields',
            new_name='folders',
        ),
    ]
