# Generated by Django 5.1.1 on 2024-10-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_writeup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writeup',
        ),
    ]
