name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y rsync

    # Ensure the .ssh directory exists and write the SSH private key to a file
    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh  # Ensure the .ssh directory exists
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_private_key
        chmod 600 ~/.ssh/ec2_private_key

    - name: Sync files to EC2 Server
      run: |
        rsync -avz --delete -e "ssh -i ~/.ssh/ec2_private_key" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to your project directory
          cd ${{ secrets.TARGET_DIR }}

          # Restart Gunicorn service
          sudo systemctl restart gunicorn
